clearRequests: true # Remove EVERY data from the database where requests are when the plugin is going to disable

messages: # Some messages support placeholders like {player} (more placeholders soon)
  playerOnlyCommand: "Este comando no se puede usar desde consola!"
  userDisconnected: "&cEl jugador que te mando solicitud de tp se desconecto!"
  userDisconnectedOrNotFound: "&cEl jugador esta desconectado o no existe!"
  userAutoTpException: "&cNo puedes mandarte una solicitud de tp a ti mismo!"
  pendingRequestException: "&cEste jugador ya tiene una solicitud de tp tuya!"
  maxTpRequests: "&cEl usuario al que le mandaste solicitud de tp tiene muchas solicitudes!"
  noTpRequest: "&cNo tienes una solicitud de ese usuario."
  noTpRequests: "&cNo tienes solicitudes de tp para aceptar o rechazar."
  requestSentOrigin: "&6Has enviado una solicitud de tp a &r&l{player}."
  requestSentDestination: "&a{player} &6quiere teletransportarse hacia ti."
  requestAcceptedDestination: "&6Has &aaceptado &6ela solicitud de tp de &r&l{player}"
  requestAcceptedOrigin:  "&6El jugador &r&l{player}&r &6ha &aaceptado &ftu solicitud de tp!"
  requestDeniedDestination: "&6Has &crechazado &6la solicitud de tp de &r&l{player}"
  requestDeniedOrigin: "&6El jugador &r&l{player}&r &6ha &crechazado &ftu solicitud de tp!"

