name: TpaPlugin
version: '2.0.0-rc5'
main: dev.rumble.tpaplugin.TpaPlugin
api-version: '1.21'
author: "pyrumble"

commands:
  tpa:
    description: "Solicita teletransportarte a un usuario"
    usage: "/tpa <jugador>"
  tpaaccept:
    description: "Acepta una solicitud de tp"
    usage: "/tpaaccept <jugador>"
  tpadeny:
    description: "Rechaza una solicitud de tp"
    usage: "/tpadeny <jugador>"
  tpahere:
    description: "Show your received tp requests"
    usage: "/tpahere"
  tpaplugin:
    description: "tpaplugin subcommands"
    usage: "/tpaplugin <reload, ?>"